services:
  api:
    platform: linux/amd64
    build: .
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    networks:
      - compoundmanager
    depends_on:
      - db

  db:
    image: postgres
    platform: linux/amd64
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - compoundmanager

networks:
  compoundmanager: