services:
  api:
    platform: linux/amd64
    build: .
    environment:
      - PYTHONPATH=/app/api
      - DJANGO_SETTINGS_MODULE=config.settings
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    networks:
      - compoundmanager
    depends_on:
      - db

  frontend:
    image: node:23-bookworm-slim
    platform: linux/amd64
    working_dir: /app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - compoundmanager-node_modules:/app/node_modules
    networks:
      - compoundmanager
    command: sh -c "npm install && npm start"

  db:
    image: postgres
    platform: linux/amd64
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - compoundmanager

networks:
  compoundmanager:

volumes:
  compoundmanager-node_modules:
