# Generated by Django 5.2 on 2025-04-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('compound_id', models.AutoField(primary_key=True, serialize=False)),
                ('smiles', models.CharField(unique=True)),
                ('data', models.JSONField(null=True)),
            ],
        ),
    ]
